project_name: proton-calendar-bridge

before:
  hooks:
    - go mod tidy

builds:
  - id: bridge
    main: ./cmd/proton-calendar-bridge
    binary: proton-calendar-bridge
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sevenofnine/proton-calendar-bridge/internal/version.Version={{.Version}}
      - -X github.com/sevenofnine/proton-calendar-bridge/internal/version.Commit={{.Commit}}
      - -X github.com/sevenofnine/proton-calendar-bridge/internal/version.BuildDate={{.Date}}

archives:
  - formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: checksums.txt

changelog:
  use: git
